// Test helper utilities
import { vi } from 'vitest';

/**
 * Create a mock paper object for testing
 * Note: id is not included by default - let IndexedDB auto-generate it
 */
export const createMockPaper = (overrides = {}) => {
  return {
    title: 'Test Paper',
    authors: ['John Doe', 'Jane Smith'],
    year: 2024,
    doi: '10.1234/test',
    tags: ['machine-learning', 'ai'],
    readingStatus: 'To Read',
    notes: 'Test notes',
    pdfData: null,
    relatedPaperIds: [],
    // createdAt and updatedAt will be auto-generated by addPaper if not provided
    ...overrides
  };
};

/**
 * Create multiple mock papers
 */
export const createMockPapers = (count = 5) => {
  return Array.from({ length: count }, (_, i) => createMockPaper({
    title: `Test Paper ${i + 1}`,
    year: 2024 - i,
    tags: i % 2 === 0 ? ['machine-learning'] : ['deep-learning'],
    readingStatus: i % 3 === 0 ? 'Reading' : 'To Read'
  }));
};

/**
 * Create a mock collection
 * Note: id is not included by default - let IndexedDB auto-generate it
 */
export const createMockCollection = (overrides = {}) => {
  return {
    name: 'Test Collection',
    // icon and color will be auto-generated by addCollection if not provided
    filters: {
      status: 'Reading',
      tags: ['machine-learning'],
      searchTerm: ''
    },
    // createdAt will be auto-generated by addCollection if not provided
    ...overrides
  };
};

/**
 * Wait for async operations
 */
export const waitFor = (ms = 0) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Mock fetch for DOI API calls
 */
export const mockFetch = (data, ok = true) => {
  global.fetch = vi.fn(() =>
    Promise.resolve({
      ok,
      json: () => Promise.resolve(data),
      text: () => Promise.resolve(JSON.stringify(data))
    })
  );
};

/**
 * Reset all mocks
 */
export const resetAllMocks = () => {
  vi.clearAllMocks();
  localStorage.clear();
};

/**
 * Mock authentication state
 */
export const setMockAuth = (authenticated = true, user = null) => {
  if (authenticated) {
    localStorage.setItem('citavers_access_token', 'mock-access-token');
    if (user) {
      localStorage.setItem('citavers_user', JSON.stringify(user));
    }
  } else {
    localStorage.removeItem('citavers_access_token');
    localStorage.removeItem('citavers_refresh_token');
    localStorage.removeItem('citavers_user');
  }
};

/**
 * Clear mock authentication state
 */
export const clearMockAuth = () => {
  localStorage.removeItem('citavers_access_token');
  localStorage.removeItem('citavers_refresh_token');
  localStorage.removeItem('citavers_user');
};

/**
 * Mock cloud sync state
 */
export const setMockSyncEnabled = (enabled = true) => {
  localStorage.setItem('citavers_sync_mode', enabled ? 'cloud' : 'local');
};

/**
 * Clear mock sync state
 */
export const clearMockSync = () => {
  localStorage.removeItem('citavers_sync_mode');
  localStorage.removeItem('citavers_last_synced_at');
  localStorage.removeItem('citavers_client_id');
  localStorage.removeItem('citavers_pending_changes');
  localStorage.removeItem('citavers_sync_in_progress');
};

/**
 * Create a mock fetch response
 */
export const createMockFetchResponse = (data, ok = true, status = 200) => {
  return Promise.resolve({
    ok,
    status,
    json: () => Promise.resolve(data),
    text: () => Promise.resolve(JSON.stringify(data)),
    headers: new Headers({
      'Content-Type': 'application/json'
    })
  });
};

/**
 * Create a mock annotation object
 */
export const createMockAnnotation = (overrides = {}) => {
  return {
    paperId: 1,
    type: 'highlight',
    pageNumber: 1,
    color: 'yellow',
    textContent: 'Highlighted text',
    ...overrides
  };
};

