name: Coverage

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30
    
    - name: Comment coverage on commit
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          // Check if coverage summary exists
          const summaryPath = './coverage/coverage-summary.json';
          if (!fs.existsSync(summaryPath)) {
            console.log('Coverage summary not found, skipping comment');
            return;
          }
          
          const coverage = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
          const total = coverage.total;
          
          const emoji = total.lines.pct >= 80 ? '🟢' : total.lines.pct >= 60 ? '🟡' : '🔴';
          
          console.log(`${emoji} Coverage: ${total.lines.pct}% lines`);

